<?php
$title = 'My albums';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a class="btn btn-success" href="<?php echo $this->url('album', array('action'=>'add'));?>">
        Add new album
    </a>
</p>

<table class="table">
    <caption>
        This is the description of the album list and here it is centralized on the screen
    </caption>
    <thead>
        <tr>
            <th>Title</th>
            <th>Artist</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($albums as $album) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($album->title);?></td>
            <td><?php echo $this->escapeHtml($album->artist);?></td>
            <td>
                <a class="btn btn-warning" href="<?php echo $this->url('album',
                    array('action'=>'edit', 'id' => $album->id));?>">Edit</a>
                <a class="btn btn-danger" href="<?php echo $this->url('album',
                    array('action'=>'delete', 'id' => $album->id));?>">Delete</a>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>